apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    app: rabbitmq
    project: roboshop
    tier: db
spec:
  selector:
    app: rabbitmq
    project: roboshop
    tier: db
  ports:
  - protocol: TCP
    port: 6379 #service-port
    targetPort: 6379 #container-port
