name: catalogue

replicaCount: 2

image:
  repository: triallwgji5.jfrog.io/roboshop/catalogue
  tag: latest

service:
  port: 8080

env:
  - name: MONGO_HOST
    value: mongodb
hpa:
  minReplicas: 1
  maxReplicas: 5
  cpuThreshold: 70
