deployment:                                            # Custom key (usually part of Helm values.yaml)

  imageURL: triallwgji5.jfrog.io/docker/roboshop/mongodb   # MongoDB Docker image stored in AWS ECR

  imageVersion: 1.0.0                                 # Image tag/version to be used for deployment
