deployment:                                           # Custom key (used in Helm values or config file)

  imageURL: triallwgji5.jfrog.io/docker/roboshop/mysql   # Docker image stored in AWS ECR

  imageVersion: 1.0.0                                # Image tag/version used for deployment
