apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
  labels:
    app: mysql
    project: roboshop
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      project: roboshop
      tier: db
  template:
    metadata:
      labels:
        app: mysql
        project: roboshop
        tier: db
    spec:
      containers:
      - name: mysql
        image: "{{ .Values.deployment.imageURL}}:{{ .Values.deployment.imageVersion}}"
        imagePullPolicy: Always
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "RoboShop@1"
        - name: MYSQL_DATABASE
          value: "roboshop"
